### PR TITLE
Build fixes:

### PR DESCRIPTION
**Pull request by ksedgwic**
1. added slip39_{wordlist,mnemonics,rs1024,encrypt,shamir}.c to SRCS
2. added -l crypto to %.out rule
3. removed slip39_test.c from repo since it is generated
4. added slip39 binary and slip39_tests.c to clean target

Signed-off-by: Ken Sedgwick <ken@bonsai.com>

### CODE REVIEW

**Comment by ChristopherA** [comment]
Still having build problems on MacOS.

So far got further doing before executing `make check`.

```
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"
```

-- Christopher Allen

**Comment by ChristopherA** [comment]
got further for the above, but still not building on MacOS:

```
$ make clean
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C randombytes clean
rm -f librandombytes.a randombytes.o test test.o
rm -f *.o *.gch *.a *.out slip39 slip39_tests.c
✔ ~/projects/github/BlockchainCommons/sss [build-fixes-signed|✚ 1] 
15:20 $ make check
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C randombytes librandombytes.a
cc -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -I/usr/local/opt/openssl/include  -c -o randombytes.o randombytes.c
randombytes.c:185:10: warning: Using arc4random system call [-W#pragma-messages]
# pragma message("Using arc4random system call")
         ^
1 warning generated.
ar -rcs librandombytes.a randombytes.o
cc -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -funroll-loops -I/usr/local/opt/openssl/include  -c -o hazmat.o hazmat.c
cc -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -I/usr/local/opt/openssl/include  -c -o randombytes.o randombytes.c
randombytes.c:185:10: warning: Using arc4random system call [-W#pragma-messages]
# pragma message("Using arc4random system call")
         ^
1 warning generated.
cc -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -I/usr/local/opt/openssl/include  -c -o sss.o sss.c
cc -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -I/usr/local/opt/openssl/include  -c -o tweetnacl.o tweetnacl.c
cc -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -I/usr/local/opt/openssl/include  -c -o slip39_wordlist.o slip39_wordlist.c
In file included from slip39_wordlist.c:4:
./slip39_wordlist_english.h:213:7: warning: no newline at end of file [-Wnewline-eof]
#endif
      ^
1 warning generated.
cc -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -I/usr/local/opt/openssl/include  -c -o slip39_mnemonics.o slip39_mnemonics.c
cc -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -I/usr/local/opt/openssl/include  -c -o slip39_rs1024.o slip39_rs1024.c
cc -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -I/usr/local/opt/openssl/include  -c -o slip39_encrypt.o slip39_encrypt.c
cc -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -I/usr/local/opt/openssl/include  -c -o slip39_shamir.o slip39_shamir.c
cc -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -I/usr/local/opt/openssl/include  -c -o test_hazmat.o test_hazmat.c
cc -o test_hazmat.out -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -L/usr/local/opt/openssl/lib test_hazmat.o randombytes/librandombytes.a hazmat.o randombytes.o sss.o tweetnacl.o slip39_wordlist.o slip39_mnemonics.o slip39_rs1024.o slip39_encrypt.o slip39_shamir.o   -lcrypto
./test_hazmat.out
cc -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -I/usr/local/opt/openssl/include  -c -o test_sss.o test_sss.c
cc -o test_sss.out -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -L/usr/local/opt/openssl/lib test_sss.o randombytes/librandombytes.a hazmat.o randombytes.o sss.o tweetnacl.o slip39_wordlist.o slip39_mnemonics.o slip39_rs1024.o slip39_encrypt.o slip39_shamir.o   -lcrypto
./test_sss.out
cc -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -I/usr/local/opt/openssl/include  -c -o test_interpolate.o test_interpolate.c
cc -o test_interpolate.out -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -L/usr/local/opt/openssl/lib hazmat.o test_interpolate.o randombytes/librandombytes.a  
./test_interpolate.out
test lagrage orthogonality: pass
test lagrage zeros and ones: pass
test simple interpolation: pass
cc -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -I/usr/local/opt/openssl/include  -c -o test_slip39_wordlist.o test_slip39_wordlist.c
In file included from test_slip39_wordlist.c:6:
./slip39_wordlist_english.h:213:7: warning: no newline at end of file [-Wnewline-eof]
#endif
      ^
1 warning generated.
cc -o test_slip39_wordlist.out -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -L/usr/local/opt/openssl/lib test_slip39_wordlist.o slip39_wordlist.o randombytes/librandombytes.a  
./test_slip39_wordlist.out
Test lookups: pass
Test toWords and fromWords: pass
cc -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -I/usr/local/opt/openssl/include  -c -o test_slip39_buffer.o test_slip39_buffer.c
test_slip39_buffer.c:56:5: warning: no previous prototype for function 'test_encode_decode_buffer' [-Wmissing-prototypes]
int test_encode_decode_buffer() {
    ^
1 warning generated.
cc -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -I/usr/local/opt/openssl/include  -c -o slip39_buffer.o slip39_buffer.c
cc -o test_slip39_buffer.out -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -L/usr/local/opt/openssl/lib test_slip39_buffer.o slip39_buffer.o randombytes/librandombytes.a  
./test_slip39_buffer.out
test encode decode buffer: pass
cc -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -I/usr/local/opt/openssl/include  -c -o test_slip39_shamir.o test_slip39_shamir.c
test_slip39_shamir.c:54:2: warning: no newline at end of file [-Wnewline-eof]
}
 ^
1 warning generated.
cc -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -I/usr/local/opt/openssl/include  -c -o test_random.o test_random.c
gcc test_slip39_shamir.o slip39_shamir.o hazmat.o test_random.o -o test_slip39_shamir.out -lcrypto
ld: library not found for -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [test_slip39_shamir.out] Error 1
rm test_hazmat.o test_sss.o
```

-- Christopher Allen

**Comment by ChristopherA** [comment]
@howech — I've still not been able to build this library on the Mac. Exporting the LDFLAGS and CPPFLAGS above helps, but the make file still can't find ssl's crypt.

Any ideas on what other export flags may be configured on your machine that allow your make to function?

**Comment by howech** [comment]
I don't have a lot of experience with macs, so I am not really in a position to help much. 

I didn't do anything to explicitly bring in openssl libraries - in truth it was because I expected someone to object and want some kind of self-contained implementation for the pbkd2 stuff that I am pulling in from it. If you have not done so already, you may have to actively install openssl on your machine (https://franz.com/support/openssl-mac.lhtml)

I looked around on the web a little bit and saw this posting that claimes that just doing a "brew install openssl" neglects the crucial step of putting its include files in a place that the compiler can find it: https://medium.com/@timmykko/using-openssl-library-with-macos-sierra-7807cfd47892

**Comment by ChristopherA** [comment]
@howech — thanks for that link — I search all over but didn't see that one.

I thought the problem with the link locations would be solved with those export flags in https://github.com/BlockchainCommons/sss/pull/5#issuecomment-543382609 but they did not.

I'll try the symbolic link method next.

**Comment by ChristopherA** [comment]
I tried the symbolic links as suggested in the post, but using 2 of the 3 resulted in no change to the make error.

These I did do:

```
ln -s /usr/local/opt/openssl/include/openssl /usr/local/include
ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
```

However, last symbolic link they suggest fails with an error:

```
$ ln -s /usr/local/Cellar/openssl/1.0.2t/include/openssl /usr/bin/openssl/`
ln: /usr/bin/openssl/: Not a directory
```

I'm not sure how to address that one.

The result of this command shows the paths that clang is using:

```
$ clang -x c -v -E /dev/null
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.14.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name null -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-sdk-version=10.14 -target-cpu penryn -dwarf-column-info -debugger-tuning=lldb -ggnu-pubnames -target-linker-version 512.4 -v -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -Wno-framework-include-private-from-public -Wno-atimport-in-framework-header -Wno-extra-semi-stmt -Wno-quoted-include-in-framework-header -fdebug-compilation-dir /Users/christophera/projects/github/BlockchainCommons/sss -ferror-limit 19 -fmessage-length 89 -stack-protector 1 -mdarwin-stkchk-strong-link -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fobjc-runtime=macosx-10.14.0 -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o - -x c /dev/null
clang -cc1 version 11.0.0 (clang-1100.0.33.8) default target x86_64-apple-darwin18.7.0
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include"
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
End of search list.
# 1 "/dev/null"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 362 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "/dev/null" 2
```

Any ideas?

**Comment by ChristopherA** [comment]
For reference for some else trying to help here, along with the symlinks above, I currently have active (as suggested by `brew info openssl`)

```
export PATH="/usr/local/opt/openssl/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"
```

-- Christopher Allen

**Comment by ChristopherA** [comment]
As per @msgilligan patches in https://github.com/msgilligan/sss/commit/61243a63143676614cc2963c2234772e89804458 just hard coding the library locations does compile, so the problem appears to be that the make file is not using the exported LDFLAGS="-L/usr/local/opt/openssl/lib" CPPFLAGS="-I/usr/local/opt/openssl/include" properly.

**Comment by ChristopherA** [comment]
Actually, @msgilligan's hard coded links works for `make check` however, `make slip39` fails:

```
$ make slip39
ar -rcs libslip39.a randombytes/librandombytes.a hazmat.o randombytes.o sss.o tweetnacl.o slip39_wordlist.o slip39_mnemonics.o slip39_rs1024.o slip39_encrypt.o slip39_shamir.o
cc -o slip39 -g -O2 -m64 -std=c99 -pedantic -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wformat -Wformat-security -Werror=format-security -Wstrict-prototypes -Wmissing-prototypes -D_FORTIFY_SOURCE=2 -fPIC -fno-strict-overflow -L/usr/local/opt/openssl/lib slip39_cli.c libslip39.a randombytes/librandombytes.a   -lcrypto
ld: warning: ignoring file libslip39.a, building for macOS-x86_64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture x86_64:
  "_combine_mnemonics", referenced from:
      _combine in slip39_cli-fbcf81.o
  "_generate_mnemonics", referenced from:
      _generate in slip39_cli-fbcf81.o
  "_parse_words", referenced from:
      _combine in slip39_cli-fbcf81.o
  "_slip39_word", referenced from:
      _print_words in slip39_cli-fbcf81.o
      _generate in slip39_cli-fbcf81.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [slip39] Error 1
```

**Comment by ksedgwic** [comment]
@howech @ChristopherA I'm also worried about OpenSSL wrt embedded systems (eg Arduino).

The prior slip39 library used https://github.com/trezor/trezor-crypto for these function.  I was able to build this library for arduino.  What do you think about using trezor-crypto instead of OpenSSL?

Other suggestions?

Thanks!

**Comment by ksedgwic** [comment]
Looks like wolfSSL is arduino friendly as well, thoughts?
https://github.com/wolfssl/wolfssl/

**Comment by ksedgwic** [comment]
@ChristopherA Looks like wolfSSL is Licensed under "GPLv2 or a standard commercial license".
https://github.com/wolfSSL/wolfssl/blob/master/LICENSING

Will this work for this project?

**Comment by ChristopherA** [comment]
> Licensed under "GPLv2

Unfortunately, some parties, in particular HTC, will be uncomfortable with a copyleft license.

Can we grab just the files we need? Or even a specific version of the file that has been copied elsewhere, for instance the secp256k1 library has a sha(256) from a particular open source commit of openSSL.

-- Christopher Allen

**Pull request merged**
